# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=128)),
                ('nit', models.IntegerField(blank=True, null=True)),
                ('representante1', models.CharField(blank=True, max_length=100, null=True)),
                ('representante2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('celular1', models.CharField(blank=True, max_length=100, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo1', models.CharField(blank=True, max_length=100, null=True)),
                ('correo2', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion1', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('id_modbus', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre_punto', models.CharField(blank=True, max_length=256, null=True)),
                ('tipo_medidor', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_medidor', models.CharField(blank=True, db_column='IP_medidor', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('version_firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entreda_operacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasarela',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(blank=True, db_column='MAC', max_length=256, null=True)),
                ('referencia', models.CharField(blank=True, max_length=256, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_pasarela', models.CharField(blank=True, db_column='IP_pasarela', max_length=256, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('version_firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrada_operacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'pasarela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationRegistrationprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40)),
                ('activated', models.IntegerField()),
            ],
            options={
                'db_table': 'registration_registrationprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysDiagrams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_principal', models.BigIntegerField()),
                ('id_diagram', models.BigIntegerField()),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definicion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sys_diagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('perfil', models.CharField(max_length=100)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vl1_n', models.FloatField(blank=True, db_column='VL1_n', null=True)),
                ('vl2_n', models.FloatField(blank=True, db_column='VL2_n', null=True)),
                ('vl3_n', models.FloatField(blank=True, db_column='VL3_n', null=True)),
                ('vl1_l2', models.FloatField(blank=True, db_column='VL1_L2', null=True)),
                ('vl2_l3', models.FloatField(blank=True, db_column='VL2_L3', null=True)),
                ('vl3_l1', models.FloatField(blank=True, db_column='VL3_L1', null=True)),
                ('il1', models.FloatField(blank=True, db_column='IL1', null=True)),
                ('il2', models.FloatField(blank=True, db_column='IL2', null=True)),
                ('il3', models.FloatField(blank=True, db_column='IL3', null=True)),
                ('f', models.FloatField(blank=True, db_column='F', null=True)),
                ('fp', models.FloatField(blank=True, db_column='FP', null=True)),
                ('pa', models.FloatField(blank=True, db_column='PA', null=True)),
                ('pq', models.FloatField(blank=True, db_column='PQ', null=True)),
                ('ps', models.FloatField(blank=True, db_column='PS', null=True)),
                ('ea', models.FloatField(blank=True, db_column='EA', null=True)),
                ('eq', models.FloatField(blank=True, db_column='EQ', null=True)),
                ('es', models.FloatField(blank=True, db_column='ES', null=True)),
                ('disparo', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('tiempo', models.DateTimeField(blank=True, null=True)),
                ('pal1', models.FloatField(blank=True, db_column='PAL1', null=True)),
                ('pal2', models.FloatField(blank=True, db_column='PAL2', null=True)),
                ('pal3', models.FloatField(blank=True, db_column='PAL3', null=True)),
            ],
            options={
                'db_table': 'variable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationSupervisedregistrationprofile',
            fields=[
                ('registrationprofile_ptr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestionMonitev.RegistrationRegistrationprofile')),
            ],
            options={
                'db_table': 'registration_supervisedregistrationprofile',
                'managed': False,
            },
        ),
    ]
